#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          predicates:
#            - Path=/customers/**
#          uri: http://localhost:8081
#        - id: r2
#          predicates:
#            - Path=/accounts/**
#          uri: http://localhost:8082
#
#server:
#  port: 8888
#
